// Quando eu quero modelar um dado, eu crio uma interface para ele.
export interface Hotel {
  id?: number; // Optional if auto-generated by the database
  name: string;
  stars: number;
  latitude: string;
  longitude: string;
  description?: string; // Optional as it's nullable
  address: string;
  district?: string; // Optional as it's nullable
  city: string;
  state: string;
  country: string;
  placeId: string;
  thumb?: string; // Optional as it's nullable
  images?: string[]; // Stored as JSON
  amenities?: string[]; // Stored as JSON
  pois?: string[]; // Stored as JSON
  reviews?: Review[]; // Stored as JSON, assuming a structure for reviews
  createdAt: string; // ISO 8601 date string
  updatedAt?: string; // Optional as it's nullable, ISO 8601 date string
  cnpj?: string; // Optional as it's nullable
}

interface Review {
  rating: number;
  comment: string;
  user: string;
}
